[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif32 @ 4.20017.260907+sha.dcc1105b

monitor_speed = 115200
